Shop.PL/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Shop.BLL.Services.DepartmentServices;
using Shop.BLL.Services.Dtos.Employee;
using Shop.BLL.Services.EmployeeServices;
using Shop.DAL.Entites.Employee;
using Shop.PL.Models;

namespace Shop.PL.Controllers
{
    [Authorize]
    public class EmployeeController : Controller
    {
        private readonly IEmployeeService _employeeService;
        private readonly IDepartmentServices _departmentServices;
        private readonly ILogger<CreateUpdateEmployeeDto> _logger;

        public EmployeeController(IEmployeeService employeeService
           , IDepartmentServices departmentServices
            ,ILogger<CreateUpdateEmployeeDto> logger)
        {
            _employeeService = employeeService;
            _departmentServices = departmentServices;
            _logger = logger;
        }
        #region Index
        public IActionResult Index(string search)
        {
            var Employees = _employeeService.GetEmployee(search);

            return View(Employees);
        }
        #endregion


        #region Details

        public IActionResult Details(int? id)
        {
            ViewData["Departments"] = _departmentServices.GetAllDepartment();
            if (id == null)
                return BadRequest();
            var Employee = _employeeService.GetEmployeeById(id);
            if (Employee == null)
                return NotFound();
            return View(Employee);
        }
        #endregion

        #region Edit
        public IActionResult Edit(int? id)
        {
            ViewData["Departments"] = _departmentServices.GetAllDepartment();
            if (id == null)
                return BadRequest();
            var Employee = _employeeService.GetEmployeeById(id);
            if (Employee == null)
                return NotFound();
            //return View(Employee);
            return View(new CreateUpdateEmployeeDto()
            {
                Address = Employee.Address,
                DepartmentId = Employee.DepartmentID,
                HiringDate = Employee.HiringDate,
                Age = Employee.Age,
                CreatedBy = Employee.CreatedBy,
                CreatedOn = Employee.CreatedOn,
                Email = Employee.Email,
                EmployeeType = Employee.EmployeeType,
                Gender = Employee.Gender,
                Id = Employee.Id,
                IsActive = Employee.IsActive,
                LastModifiedBy = Employee.LastModifiedBy,
                LastModifiedOn = Employee.LastModifiedOn,
                Name = Employee.Name,
                PhoneNumber = Employee.PhoneNumber,
                Salary = Employee.Salary,
            });

        }
        [HttpPost]
        public IActionResult Edit(int? id, CreateUpdateEmployeeDto employeeDto)
        {
            try
            {
                if (employeeDto.Id != id)
                    return BadRequest();
                if (ModelState.IsValid)
                {
                    var Result = _employeeService.Update(employeeDto) > 0;
                    if (Result)
                        TempData["SuccessMessage"] = "Employee is Updated";
                    else
                        TempData["ErrorMessage"] = "Something went wrong!";
                    return RedirectToAction("Index");

                }
                ModelState.AddModelError("", "Employee Not Updated");
                TempData["ErrorMessage"] = "Something went wrong!";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
                return View(employeeDto);
            }

        }
        #endregion


        #region Create
        [HttpGet]
        public IActionResult Create()
        {
            ViewData["Departments"] = _departmentServices.GetAllDepartment();
            return View();
        }
        [HttpPost]
        public IActionResult Create(CreateUpdateEmployeeDto employeeDto)
        {
            try
            {
                ViewData["Departments"] = _departmentServices.GetAllDepartment();

                if (ModelState.IsValid)
                {
                    var Result = _employeeService.Creat(employeeDto) > 0;
                    if (Result)
                        TempData["SuccessMessage"] = "Employee is Created";
                    else
                        TempData["ErrorMessage"] = "Something went wrong!";
                    return RedirectToAction("Index");

                }
                else
                    ModelState.AddModelError("", "Employee Not Updated");
                TempData["ErrorMessage"] = "Something went wrong!";
                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
                return View(employeeDto);
            }
        }

        #endregion


        #region Delete
        public IActionResult Delete(int? id)
        {
            var Message = string.Empty;
            if (id is null)
                return BadRequest();
            var Employee = _employeeService.GetEmployeeById(id.Value);
            if (Employee == null)
                return NotFound();
            var Deleted = _employeeService.Delete(id.Value);
            if (Deleted)
                TempData["DeleteMessage"] = "Department is deleted.";
            else
                TempData["ErrorMessage"] = "Something went wrong!";

            return RedirectToAction("Index");

        } 
        #endregion
    }

}

Shop.PL/Controllers/RoleController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shop.DAL.Entites.Identity;
using Shop.PL.Models.Roles;

namespace Shop.PL.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IMapper _mapper;
        private readonly UserManager<ApplicationUser> _userManager;

        public RoleController(RoleManager<IdentityRole> roleManager,
            IMapper mapper,
            UserManager<ApplicationUser> userManager)
        {
            _roleManager = roleManager;
            _mapper = mapper;
            _userManager = userManager;
        }
        #region Index
        public async Task<IActionResult> Index(string search)
        {
            if (string.IsNullOrEmpty(search))
            {
                var Role = await _roleManager.Roles.ToListAsync();
                var MappedRole = _mapper.Map<IEnumerable<IdentityRole>, IEnumerable<RoleViewModel>>(Role);
                return View(MappedRole);
            }
            else
            {
                var SearchRole = await _roleManager.FindByNameAsync(search);
                var MappedRole = _mapper.Map<IdentityRole, RoleViewModel>(SearchRole);
                return View(MappedRole);
            }

        }
        #endregion

        #region Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(RoleViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var MappedRole = _mapper.Map<RoleViewModel, IdentityRole>(model);
                    var CreateRole = await _roleManager.CreateAsync(MappedRole);
                    if (CreateRole.Succeeded)
                        return RedirectToAction("Index");
                    foreach (var Role in CreateRole.Errors)
                        ModelState.AddModelError("", Role.Description);
                }

                ModelState.AddModelError("", "Invalid Create");
            }
            catch (Exception ex)
            {

                ModelState.AddModelError("", ex.Message);
            }
                return View(model);
        }
        #endregion

        #region Details
        public async Task<IActionResult> Details(string Id)
        {
            if (Id is null)
                return NotFound();
            var Role= await _roleManager.FindByIdAsync(Id);
            return View(Role);

        }
        #endregion

        #region Edit
        [HttpGet]
        public async Task<IActionResult> Edit(string Id)
        {

            if (Id is null)
                return NotFound();
            var Role=await _roleManager.FindByIdAsync(Id);
            if(Role is null)
                return NotFound();

            return View(new RoleViewModel()
            {
                Id = Role.Id,
                RoleName = Role.Name
            });
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string Id,RoleViewModel model)
        {
            try
            {
                if (Id is null)
                    return NotFound();
                if (!ModelState.IsValid)
                    ModelState.AddModelError("", "Invalid Update");
                var mappedRole = _mapper.Map<RoleViewModel, IdentityRole>(model);
                var UpdateRole = await _roleManager.UpdateAsync(mappedRole);
                if (UpdateRole.Succeeded)
                    return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                
            }
                return View(model);
           
        }
        #endregion

        #region Delete
        public async Task<IActionResult> Delete(string Id)
        {
            if (Id is null)
                return NotFound();
            var Role=await _roleManager.FindByIdAsync(Id);
            if(Role is null)
                return BadRequest();
            var DeleteRole=await _roleManager.DeleteAsync(Role);
            if (DeleteRole.Succeeded)
                return RedirectToAction(nameof(Index));
            foreach (var error in DeleteRole.Errors)
                ModelState.AddModelError("", error.Description);
            return RedirectToAction(nameof(Index));
            
        }
        #endregion

        #region Add Or Remove Users
        public async Task<IActionResult> AddOrRemoveUsers(string roleId)
        {
            ViewData["RoleId"] = roleId;
            var role = await _roleManager.FindByIdAsync(roleId);
            if (role == null)
            {
                return NotFound();
            }

            var users = await _userManager.Users.ToListAsync();
            var usersInRole = new List<UserInRoleViewModel>();

            foreach (var user in users)
            {
                var isInRole = await _userManager.IsInRoleAsync(user, role.Name);
                usersInRole.Add(new UserInRoleViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName,
                    IsSelected = isInRole
                });
            }

            ViewData["RoleId"] = roleId;
            return View(usersInRole);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrRemoveUsers(string RoleId, List<UserInRoleViewModel> RoleinUser)
        {
            var role = await _roleManager.FindByIdAsync(RoleId);
            if (role == null)
            {
                return NotFound();
            }

            foreach (var user in RoleinUser)
            {
                var appUser = await _userManager.FindByIdAsync(user.UserId);
                if (appUser != null)
                {
                    if (user.IsSelected && !await _userManager.IsInRoleAsync(appUser, role.Name))
                    {
                        // Add user to the role if they are selected and not already in the role
                        await _userManager.AddToRoleAsync(appUser, role.Name);
                    }
                    else if (!user.IsSelected && await _userManager.IsInRoleAsync(appUser, role.Name))
                    {
                        // Remove user from the role if they are not selected and are currently in the role
                        await _userManager.RemoveFromRoleAsync(appUser, role.Name);
                    }
                }
            }

            return RedirectToAction("Index");
        }
        #endregion

        #region AccessDenid
        public IActionResult AccessDenied()
        {
            return View();
        } 
        #endregion

    }
}

Shop.PL/Controllers/UserController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages;
using Shop.DAL.Entites.Identity;
using Shop.PL.Models.Users;

namespace Shop.PL.Controllers
{
        [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {

        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IMapper _mapper;

        public UserController(UserManager<ApplicationUser> userManager,
            IMapper mapper)
        {
            _userManager = userManager;
            _mapper = mapper;
        }
        #region Index
        public async Task<IActionResult> Index(string SearchInput)
        {
            List<ApplicationUser> users;
            if (string.IsNullOrEmpty(SearchInput))
            {
                users = await _userManager.Users.ToListAsync();
            }
            else
            {
                users = await _userManager.Users.Where(users =>
                users.NormalizedEmail.Trim()
                .Contains(SearchInput.Trim().ToUpper())).ToListAsync();
            }
            return View(users);
        }
        #endregion

        #region Details

        public async Task<IActionResult> Details(string id,string value="Details")
        {
            if (id is null)
                return BadRequest();
            var User=await _userManager.FindByIdAsync(id);
            if (User is null)
                return NotFound();
            if (value == "Edit")
            {
                var UserViewModel = new UpdateUsersViewModel
                {
                    Id = User.Id,
                    FName = User.FirstName,
                    LName = User.LastName,
                   
                };
                return View(value, UserViewModel);
            }
            return View(value,User);
        }
        #endregion

        #region Edit

        public async Task<IActionResult> Edit(string Id)
        {
            if (Id is null)
                return NotFound();
            return await Details(Id,"Edit");

        }
        [HttpPost]
        public async Task<IActionResult> Edit(string Id,UpdateUsersViewModel model)
        {
            try
            {
                if (Id is null)
                    return NotFound();
                if (Id != model.Id)
                    return BadRequest();
                if (ModelState.IsValid)
                {
                    var User = await _userManager.FindByIdAsync(Id);
                    User.FirstName = model.FName;
                    User.LastName = model.LName;
                    await _userManager.UpdateAsync(User);
                        return RedirectToAction(nameof(Index));
                  
                }
                
            }
            catch (Exception ex)
            {
               ModelState.AddModelError("", ex.Message);

            }
                  ModelState.AddModelError("", "Invalid Update");
                  return View(model);
        }
        #endregion


        #region Delete


        public async Task<IActionResult> Delete(string id)
        {
            try
            {
                if (id is null)
                    return NotFound();
                var User = await _userManager.FindByIdAsync(id);
                if (User is null)
                    return BadRequest();
                var DeleteUser = await _userManager.DeleteAsync(User);
                if (DeleteUser.Succeeded)
                    return RedirectToAction(nameof(Index));
                foreach (var item in DeleteUser.Errors)
                    ModelState.AddModelError("", item.Description);
            }
            catch (Exception ex)
            {

                ModelState.AddModelError("", ex.Message);
            }
            return RedirectToAction(nameof(Index));
        }
        #endregion
    }
}

Shop.PL/Views/Shared/ButtonBartialView.cshtml
@model int
<td>
    <!-- Details Button -->
    <a asp-action="Details" asp-route-id="@Model" class="btn btn-warning"><i class="fas fa-eye"></i>Details</a>
</td>
<td>
    <!-- Update Button -->
    <a asp-action="Edit" asp-route-id="@Model" class="btn btn-success"><i class="fas fa-edit"></i>Update</a>
</td>
<td>
    <!-- Delete Button -->
    <form asp-action="Delete" asp-route-id="@Model" method="post" style="display:inline;">
        <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this department?');"><i class="fa-solid fa-trash"></i>Delete</button>
    </form>
</td>

Shop.PL/Views/Shared/_AuthLayOut.cshtml
<!--
Author: Colorlib
Author URL: https://colorlib.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
	<title>Creative Colorlib SignUp Form</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- Custom Theme files -->
	<link href="~/css/AuthLayout.css" rel="stylesheet" type="text/css" media="all" />
	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		<h1>Creative @ViewData["Title"]</h1>
		@RenderBody();
		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
		</div>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	<script type="text/javascript">
		toastr.options = {
			"closeButton": true,
			"debug": false,
			"newestOnTop": false,
			"progressBar": true,
			"positionClass": "toast-top-right",
			"preventDuplicates": false,
			"onclick": null,
			"showDuration": "300",
			"hideDuration": "1000",
			"timeOut": "5000",
			"extendedTimeOut": "1000",
			"showEasing": "swing",
			"hideEasing": "linear",
			"showMethod": "fadeIn",
			"hideMethod": "fadeOut"
		}
	</script>

	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Shop.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Shop.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Shop.PL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Shop.PL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Department</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                        </li>
                        <li class="nav-item ms-auto">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="LogOut">LogOut</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Shop.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>